### ISSUE TITLE
wellmap command line script does not work on windows

### ISSUE THREAD

**Issue by ajasja** [kalekundert/wellmap#35]
The `os.fork` command is not available on windows, so the command line utility does not work

```bash
$ wellmap layout.toml 
Traceback (most recent call last):
  File "C:\bin\python\anaconda64\envs\spectraplotpy\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\bin\python\anaconda64\envs\spectraplotpy\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\bin\python\anaconda64\envs\spectraplotpy\Scripts\wellmap.exe\__main__.py", line 7, in <module>
  File "C:\bin\python\anaconda64\envs\spectraplotpy\lib\site-packages\wellmap\plot.py", line 101, in main
    if os.fork() != 0:
AttributeError: module 'os' has no attribute 'fork'
```

**Comment by ajasja** [comment]
I just saw the `--foreground` option. That works, and I can even lunch it with 
`wellmap layout.toml --foreground &`
To get it in the background :)

The library looks awesome by the way!

**Comment by kalekundert** [comment]
I'm glad you found the workaround, but I should probably tweak the script so that it doesn't crash in the first place.  I'll keep this issue open until I get around to that.

**Comment by ajasja** [comment]
Thanks! One temporary fix would be to just have `--foreground` be the default behaviour on windows.
